name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write  # Mandatory for trusted publishing
      contents: read   # Required to access repository files
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Reuse Build and Validate Workflow
      uses: ./.github/workflows/build.yml
      with:
        python-version: '3.10'
        node-version: 'v18.16.0'
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
