name: Generate release

permissions:
  contents: read

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Reuse Build and Validate Workflow
        uses: ./.github/workflows/build.yml
        with:
          python-version: '3.10'
          node-version: 'v18.16.0'
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.whl,dist/*.tar.gz"
          draft: true
